# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ff18f78c54c69fe5b6a8203ede90166712960d0831d67638b955aeda1a21bce085d593f44dc479fe883798f4bf8c651bf1ad52acf0e8128effa9b346d8b650e

test:
  secret_key_base: cc35e1ad6a40f479edd071147f98b3b4fca66aea728a50cd303ba4ac8e686b3843df5bdd40d4a7ec61aa3b7c448475ef6a3e235a5bb0d4751d18d890bd669fc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
